---
- name: install the latest version of the apache
  yum:
       name: httpd
       state: latest

- name: install the latest version of net-tools for ifconfig command
  yum:
       name: net-tools 
       state: latest

- name: install the latest version of python 
  yum: 
       name: python
       state: latest

- name: install the latest version of vim
  yum:
       name: vim
       state: latest

- name: install the latest version of wget
  yum:
       name: wget
       state: latest

- name: install and configure git on all server
  include: git_config.yml
  tags: git 
